/**
 * build-static.mjs — emit dist/, a fully static ABYSS for GitHub Pages.
 *
 * GitHub Pages serves files only; it cannot run the Node server. So this build
 * removes the server from the runtime path entirely:
 *
 *   species catalogue  ->  dist/data/species.json       (read once, filtered in the browser)
 *   ocean physics      ->  dist/js/lib/ocean.js         (the SAME file the server runs)
 *   dive log           ->  localStorage                 (no database)
 *   dive telemetry     ->  computed in the browser      (no SSE)
 *
 * The physics and search modules are pure ESM with zero imports, so they run
 * unchanged in a browser. That is the whole reason a static export is possible
 * without rewriting the science — and it is why they are COPIED here rather
 * than reimplemented: one source, and the browser computes the same numbers the
 * server does, not merely similar ones.
 *
 * `public/js/core/mode.js` carries the switch. The repo copy says false; this
 * build overwrites it with true so the client knows there is no API to call.
 *
 *   node scripts/build-static.mjs [--out=dist]
 */
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  rmSync,
  existsSync,
  readdirSync,
  statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SPECIES } from '../server/data/species.mjs';
import { ZONES, CHALLENGER_DEEP } from '../server/ocean.mjs';
import { imageFor, imageStats, loadImages } from '../server/images.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');

const outArg = process.argv.find((a) => a.startsWith('--out='));
const OUT = join(ROOT, outArg ? outArg.slice(6) : 'dist');

const log = (msg) => console.log(`  ${msg}`);

/* ------------------------------------------------------------------ *
 * Build
 * ------------------------------------------------------------------ */

function build() {
  if (existsSync(OUT)) rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  /* 1. The site itself. */
  cpSync(join(ROOT, 'public'), OUT, { recursive: true });
  log(`copied public/ -> ${OUT.replace(ROOT, '.')}`);

  /* 2. Shared modules, at the SAME paths the dev server exposes them.
   *    One URL resolves in both modes, so the client has no branch for it. */
  mkdirSync(join(OUT, 'js', 'lib'), { recursive: true });
  cpSync(join(ROOT, 'server', 'ocean.mjs'), join(OUT, 'js', 'lib', 'ocean.js'));
  cpSync(join(ROOT, 'server', 'data', 'search.mjs'), join(OUT, 'js', 'lib', 'search.js'));
  log('copied ocean.mjs + search.mjs -> js/lib/ (same URLs as the dev server)');

  /* 3. Static mode flag. */
  writeFileSync(
    join(OUT, 'js', 'core', 'mode.js'),
    `/**
 * GENERATED by scripts/build-static.mjs — do not edit.
 *
 * true  = no API exists; the browser computes physics, filters the catalogue
 *         from JSON, keeps the dive log in localStorage and simulates telemetry.
 * false = the Node server is present and answers /api/*.
 */
export const STATIC_MODE = true;
export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`,
  );
  log('wrote js/core/mode.js (STATIC_MODE = true)');

  /* 4. The catalogue, as JSON the browser filters itself. */
  const images = loadImages();
  const species = SPECIES.map((s) => ({
    slug: s.slug,
    common: s.common,
    scientific: s.scientific,
    family: s.family ?? null,
    group: s.group ?? null,
    zone: s.zone,
    depthMin: s.depthMin,
    depthMax: s.depthMax,
    sizeCm: s.sizeCm ?? null,
    massKg: s.massKg ?? null,
    bioluminescent: !!s.bioluminescent,
    iucn: s.iucn ?? null,
    diet: s.diet ?? null,
    sprite: s.sprite,
    accent: s.accent,
    blurb: s.blurb,
    facts: s.facts ?? [],
    image: imageFor(s.slug),
  }));

  mkdirSync(join(OUT, 'data'), { recursive: true });
  writeFileSync(join(OUT, 'data', 'species.json'), JSON.stringify({ total: species.length, items: species }));

  const zones = ZONES.map((z) => ({
    id: z.id,
    name: z.name,
    alias: z.alias,
    min: z.min,
    max: z.max,
    accent: z.accent,
    summary: z.summary,
    speciesCount: species.filter((s) => s.zone === z.id).length,
  }));

  const stats = {
    species: species.length,
    bioluminescent: species.filter((s) => s.bioluminescent).length,
    shallowest: Math.min(...species.map((s) => s.depthMin)),
    deepest: Math.max(...species.map((s) => s.depthMax)),
    zones: zones.length,
    withPhoto: imageStats().withPhoto,
  };

  writeFileSync(
    join(OUT, 'data', 'catalogue.json'),
    JSON.stringify({
      zones,
      stats,
      limits: { deepest: CHALLENGER_DEEP, deepestFish: 8336, meanOceanDepth: 3688 },
    }),
  );

  log(`wrote data/species.json (${species.length} species, ${stats.withPhoto} with photographs)`);
  log(`wrote data/catalogue.json (${zones.length} zones)`);
  void images;

  /* 5. No server means no server-side routes to accidentally leave behind. */
  writeFileSync(join(OUT, '.nojekyll'), '');
  log('wrote .nojekyll (so Pages serves _-prefixed paths untouched)');

  /* 6. Sizes, for the build log. */
  const stats2 = walk(OUT);
  log(`\n  dist/ ready — ${stats2.files} files, ${(stats2.bytes / 1024 / 1024).toFixed(1)} MB`);
}

/**
 * Directory size and file count.
 *
 * `readdirSync(withFileTypes: true)` returns Dirent objects, which carry the
 * name and type but NOT the size — reading `.size` off one is undefined and
 * summed to NaN. statSync is needed for the bytes.
 */
function walk(dir, out = { files: 0, bytes: 0 }) {
  for (const entry of readdirSafe(dir)) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, out);
    } else {
      out.files += 1;
      try {
        out.bytes += statSync(full).size;
      } catch {
        /* vanished mid-walk; not worth failing a build over */
      }
    }
  }
  return out;
}

function readdirSafe(dir) {
  try {
    return readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
}

/* ------------------------------------------------------------------ */

console.log('\nABYSS static build\n');
build();

// Fail loudly rather than publishing a site whose data is missing.
const required = ['index.html', 'data/species.json', 'data/catalogue.json', 'js/lib/ocean.js', 'js/core/mode.js'];
const missing = required.filter((f) => !existsSync(join(OUT, f)));
if (missing.length) {
  console.error(`\n  BUILD FAILED — missing: ${missing.join(', ')}\n`);
  process.exit(1);
}

const mode = readFileSync(join(OUT, 'js', 'core', 'mode.js'), 'utf8');
if (!mode.includes('STATIC_MODE = true')) {
  console.error('\n  BUILD FAILED — mode.js does not enable static mode\n');
  process.exit(1);
}

console.log(`  verified: all ${required.length} required outputs present, STATIC_MODE=true\n`);