/**
 * gen-credits.mjs — write CREDITS.md from the image manifest.
 *
 * CC BY and CC BY-SA require the creator to be named wherever the work is used.
 * The site does that on every card, but a repository that redistributes the
 * files should carry the attributions too, in one place, so someone cloning it
 * can see at a glance what is reusable and under what terms.
 *
 * Generated rather than hand-written so it cannot fall out of step with
 * species-images.json.
 *
 *   node scripts/gen-credits.mjs
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadImages } from '../server/images.mjs';
import { SPECIES } from '../server/data/species.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const images = loadImages() ?? {};
const bySlug = new Map(SPECIES.map((s) => [s.slug, s]));

const rows = Object.entries(images)
  .map(([slug, img]) => ({ slug, img, sp: bySlug.get(slug) }))
  .filter((r) => r.sp)
  .sort((a, b) => a.sp.common.localeCompare(b.sp.common));

const noCreditNeeded = rows.filter((r) => /^(cc0|public domain)/i.test(r.img.licence));
const needsCredit = rows.filter((r) => !/^(cc0|public domain)/i.test(r.img.licence));

const lines = [];

lines.push('# Credits');
lines.push('');
lines.push('## Code');
lines.push('');
lines.push('The application code is MIT licensed — see [LICENSE](LICENSE).');
lines.push('');
lines.push(
  'That licence covers the software: everything in `server/`, `public/js/`, `public/css/` ' +
    'and `scripts/`, together with the species text, depth ranges and field notes.',
);
lines.push('');
lines.push(
  '**It does not cover the species photographs.** Those are the work of their respective ' +
    'photographers and are used under their own licences, listed below. Reusing an image ' +
    'means complying with *that* licence, not the MIT one.',
);
lines.push('');
lines.push('The oceanographic models are transcriptions of published work:');
lines.push('');
lines.push('- **UNESCO (1983)** — *Algorithms for computation of fundamental properties of seawater*,');
lines.push('  UNESCO Technical Papers in Marine Science 44. (EOS-80 equation of state.)');
lines.push('- **Mackenzie, K. V. (1981)** — Nine-term equation for sound speed in the oceans,');
lines.push('  *J. Acoust. Soc. Am.* 70(3), 807–812.');
lines.push('- **Saunders, P. M. (1981)** — Practical conversion of pressure to depth,');
lines.push('  *J. Phys. Oceanogr.* 11, 573–574.');
lines.push('- **Jerlov, N. G. (1976)** — *Marine Optics*, Elsevier. (Attenuation coefficients.)');
lines.push('');
lines.push('## Species photographs');
lines.push('');
lines.push(
  `${rows.length} of the ${SPECIES.length} species use a photograph from Wikimedia Commons. ` +
    'Each is used under its own licence, listed below with its creator. **Reusing any of these ' +
    'images requires complying with that image\'s licence, not the MIT licence covering the code.**',
);
lines.push('');

if (needsCredit.length) {
  lines.push(`### Requiring attribution (${needsCredit.length})`);
  lines.push('');
  lines.push('| Species | Creator | Licence | Source |');
  lines.push('|---|---|---|---|');
  for (const { img, sp } of needsCredit) {
    const source = img.sourceUrl ? `[Commons](${img.sourceUrl})` : '—';
    const licence = img.licenceUrl ? `[${img.licence}](${img.licenceUrl})` : img.licence;
    lines.push(`| ${sp.common} | ${img.artist || '—'} | ${licence} | ${source} |`);
  }
  lines.push('');
}

if (noCreditNeeded.length) {
  lines.push(`### No attribution required (${noCreditNeeded.length})`);
  lines.push('');
  lines.push('CC0 or public domain. Credited here anyway, because the photographers deserve it.');
  lines.push('');
  lines.push('| Species | Creator | Licence | Source |');
  lines.push('|---|---|---|---|');
  for (const { img, sp } of noCreditNeeded) {
    const source = img.sourceUrl ? `[Commons](${img.sourceUrl})` : '—';
    const licence = img.licenceUrl ? `[${img.licence}](${img.licenceUrl})` : img.licence;
    lines.push(`| ${sp.common} | ${img.artist || '—'} | ${licence} | ${source} |`);
  }
  lines.push('');
}

if (rows.length < SPECIES.length) {
  const missing = SPECIES.filter((s) => !images[s.slug]);
  lines.push(`### Species with no photograph (${missing.length})`);
  lines.push('');
  lines.push('These use a hand-drawn SVG plate instead. No freely-licensed photograph of them');
  lines.push('was found on Wikimedia Commons:');
  lines.push('');
  for (const s of missing) lines.push(`- **${s.common}** (*${s.scientific}*)`);
  lines.push('');
}

lines.push('---');
lines.push('');
lines.push('Generated by `scripts/gen-credits.mjs` from `server/data/species-images.json`.');
lines.push('');

writeFileSync(join(ROOT, 'CREDITS.md'), lines.join('\n'));
console.log(`wrote CREDITS.md — ${needsCredit.length} requiring attribution, ${noCreditNeeded.length} CC0/PD, ${SPECIES.length - rows.length} plates`);